# Generated by Django 6.0.6 on 2026-06-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la machine')),
                ('code_interne', models.CharField(max_length=20, unique=True, verbose_name='Code inventaire (ex: MAC-001)')),
                ('emplacement', models.CharField(max_length=100, verbose_name='Localisation / Atelier')),
                ('date_installation', models.DateField(blank=True, null=True, verbose_name='Date de mise en service')),
                ('statut', models.CharField(choices=[('fonctionne', 'En marche / Opérationnel'), ('panne', 'En panne / Arrêt'), ('maintenance', 'En cours de maintenance')], default='fonctionne', max_length=20, verbose_name='État actuel')),
            ],
        ),
    ]
