# Generated by Django 6.0.6 on 2026-06-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la zone')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.RemoveField(
            model_name='machine',
            name='date_installation',
        ),
        migrations.AlterField(
            model_name='machine',
            name='code_interne',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code interne'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='emplacement',
            field=models.CharField(max_length=100, verbose_name='Emplacement précis'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='statut',
            field=models.CharField(choices=[('fonctionne', 'En marche / Opérationnel'), ('panne', 'En panne / Arrêt'), ('maintenance', 'En cours de maintenance')], default='fonctionne', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='machines.zone', verbose_name='Zone / Secteur'),
        ),
    ]
