# Generated by Django 6.0.6 on 2026-06-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_zone_remove_machine_date_installation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la pièce')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence constructeur / interne')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Caractéristiques')),
                ('quantite_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('stock_minimum', models.PositiveIntegerField(default=1, verbose_name='Alerte stock minimum')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (€)')),
                ('machine_compatible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_detachees', to='machines.machine', verbose_name='Machine compatible (optionnel)')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
            },
        ),
    ]
