# Generated by Django 5.2.16 on 2026-08-24 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_section_depensebudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestataire', models.CharField(max_length=150, verbose_name='Nom du prestataire')),
                ('type_contrat', models.CharField(choices=[('maintenance', 'Contrat de maintenance'), ('assurance', 'Assurance'), ('location', 'Location / Leasing'), ('prestation', 'Prestation de service'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de contrat')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide si le contrat est à durée indéterminée / reconduction tacite.', null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Notes')),
                ('document', models.FileField(blank=True, null=True, upload_to='contrats/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Document (PDF ou image)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
    ]
