# Generated by Django 6.0.6 on 2026-06-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Problème constaté')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('type_intervention', models.CharField(choices=[('correctif', 'Correctif (Panne)'), ('preventif', 'Préventif (Entretien)')], default='correctif', max_length=20)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire / En attente'), ('en_cours', 'En cours de réparation'), ('resolu', 'Résolu / Clôturé')], default='a_faire', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Machine concernée')),
                ('technicien', models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné')),
            ],
        ),
    ]
