# Generated by Django 6.0.6 on 2026-06-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'permissions': [('can_close_intervention', 'Peut clôturer une intervention')]},
        ),
    ]
