# Generated by Django 6.0.6 on 2026-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_alter_intervention_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='machine_arretee',
            field=models.BooleanField(default=False, verbose_name='Machine arrêtée ?'),
        ),
    ]
