# Generated by Django 6.0.6 on 2026-06-23 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_intervention_machine_arretee'),
        ('machines', '0003_piecedetachee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='machine_arretee',
        ),
        migrations.AddField(
            model_name='intervention',
            name='compte_rendu',
            field=models.TextField(blank=True, null=True, verbose_name="Compte-rendu de l'intervention"),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de signalement'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='machines.machine', verbose_name='Machine'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Technicien en charge'),
        ),
        migrations.CreateModel(
            name='InterventionPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.PositiveIntegerField(default=1, verbose_name='Quantité utilisée')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.intervention')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.piecedetachee', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Pièce utilisée',
                'verbose_name_plural': 'Pièces utilisées',
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='pieces_utilisees',
            field=models.ManyToManyField(blank=True, through='interventions.InterventionPiece', to='machines.piecedetachee', verbose_name='Pièces utilisées'),
        ),
    ]
