# Generated by Django 5.2.16 on 2026-09-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0008_demandeamelioration'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeamelioration',
            name='date_cloture',
            field=models.DateTimeField(blank=True, help_text='Renseignée automatiquement quand la demande passe à Acceptée, Refusée ou Réalisée.', null=True, verbose_name='Date de clôture'),
        ),
    ]
