# Generated by Django 5.2.16 on 2026-09-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0009_demandeamelioration_date_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='nature',
            field=models.CharField(choices=[('panne', 'Panne'), ('reglage', 'Réglage'), ('nettoyage', 'Nettoyage'), ('modification', 'Modification'), ('divers', 'Divers'), ('travaux_neuf', 'Travaux Neuf')], default='panne', max_length=20, verbose_name="Nature de l'intervention"),
        ),
    ]
