# Generated by Django 5.2.16 on 2026-08-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Responsable'), ('chef_equipe', "Chef d'équipe"), ('technicien', 'Technicien de Maintenance'), ('production', 'Production / Opérateur')], default='production', max_length=20, verbose_name="Rôle au sein de l'entreprise"),
        ),
    ]
