# Generated by Django 5.2.16 on 2026-08-24 09:08

import django.db.models.deletion
from django.db import migrations, models

# Catalogue des pages/actions dont l'accès par rôle devient configurable
# depuis la page d'administration des droits (utilisateurs.views.gestion_droits),
# et les rôles autorisés PAR DÉFAUT pour chacune, choisis pour reproduire
# exactement le comportement précédent (décorateurs @bloquer_pour_role codés
# en dur dans les vues), afin que cette migration ne change rien au
# comportement de l'appli tant que l'admin ne modifie rien depuis cette page.
#
# Ces données sont dupliquées ici plutôt qu'importées depuis les vues :
# une migration ne doit jamais dépendre du code applicatif, qui peut changer
# après coup (voir la documentation Django sur les migrations de données).
FONCTIONNALITES = [
    # (code, nom, categorie, ordre)
    ('tableau_de_bord', 'Tableau de bord', 'Général', 10),
    ('declarer_panne', 'Déclarer une panne', 'Général', 20),
    ('amelioration', 'Amélioration (consulter / soumettre)', 'Général', 30),
    ('changer_statut_amelioration', "Changer le statut d'une demande d'amélioration", 'Général', 40),
    ('changer_statut_intervention', "Changer le statut d'une intervention (prendre en charge / clôturer)", 'Général', 50),

    ('maintenance_preventive_consulter', 'Maintenance Préventive (consulter)', 'Maintenance', 110),
    ('maintenance_preventive_programmer', 'Maintenance Préventive (programmer)', 'Maintenance', 120),
    ('maintenance_curative', 'Maintenance Curative', 'Maintenance', 130),
    ('machine_parc', 'Machine (parc : ajout / suppression)', 'Maintenance', 140),
    ('stock_pieces', 'Stock de Pièces', 'Maintenance', 150),
    ('analyse_preventif_curatif', 'Analyse (Préventif / Curatif)', 'Maintenance', 160),
    ('analyse_temps_arret', "Analyse des Temps d'arrêt", 'Maintenance', 170),

    ('service_generaux_batiment', 'Service Généraux - Bâtiment', 'Service Généraux', 210),

    ('budget_machine', 'Budget Machine', 'Budget', 310),
    ('budget_sections', 'Budget - Consommable / Entretien / Travaux Neuf', 'Budget', 320),
    ('contrats', 'Budget - Contrats', 'Budget', 330),
]

ROLES_AUTORISES_PAR_DEFAUT = {
    'tableau_de_bord': {'admin', 'responsable', 'technicien'},
    'declarer_panne': {'admin', 'responsable', 'technicien', 'chef_equipe'},
    'amelioration': {'admin', 'responsable', 'technicien', 'chef_equipe', 'production'},
    'changer_statut_amelioration': {'admin', 'responsable', 'technicien', 'chef_equipe', 'production'},
    'changer_statut_intervention': {'admin', 'responsable', 'technicien'},

    'maintenance_preventive_consulter': {'admin', 'responsable', 'technicien', 'chef_equipe', 'production'},
    'maintenance_preventive_programmer': {'admin', 'responsable', 'technicien'},
    'maintenance_curative': {'admin', 'responsable', 'technicien', 'chef_equipe', 'production'},
    'machine_parc': {'admin', 'responsable', 'technicien'},
    'stock_pieces': {'admin', 'responsable', 'technicien'},
    'analyse_preventif_curatif': {'admin', 'responsable'},
    'analyse_temps_arret': {'admin', 'responsable'},

    'service_generaux_batiment': {'admin', 'responsable', 'technicien', 'chef_equipe', 'production'},

    'budget_machine': {'admin', 'responsable'},
    'budget_sections': {'admin', 'responsable'},
    'contrats': {'admin', 'responsable'},
}

TOUS_LES_ROLES = ['admin', 'responsable', 'chef_equipe', 'technicien', 'production']


def creer_fonctionnalites_et_droits(apps, schema_editor):
    Fonctionnalite = apps.get_model('utilisateurs', 'Fonctionnalite')
    DroitRole = apps.get_model('utilisateurs', 'DroitRole')

    for code, nom, categorie, ordre in FONCTIONNALITES:
        fonctionnalite, _ = Fonctionnalite.objects.get_or_create(
            code=code, defaults={'nom': nom, 'categorie': categorie, 'ordre': ordre},
        )
        roles_autorises = ROLES_AUTORISES_PAR_DEFAUT.get(code, set())
        for role in TOUS_LES_ROLES:
            DroitRole.objects.get_or_create(
                fonctionnalite=fonctionnalite, role=role,
                defaults={'autorise': role in roles_autorises},
            )


def supprimer_fonctionnalites(apps, schema_editor):
    Fonctionnalite = apps.get_model('utilisateurs', 'Fonctionnalite')
    Fonctionnalite.objects.filter(code__in=[code for code, *_ in FONCTIONNALITES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code (technique)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom affiché')),
                ('categorie', models.CharField(max_length=50, verbose_name='Catégorie (regroupement dans le tableau)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DroitRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Responsable'), ('chef_equipe', "Chef d'équipe"), ('technicien', 'Technicien de Maintenance'), ('production', 'Production / Opérateur')], max_length=20, verbose_name='Rôle')),
                ('autorise', models.BooleanField(default=False, verbose_name='Autorisé ?')),
                ('fonctionnalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits', to='utilisateurs.fonctionnalite')),
            ],
            options={
                'verbose_name': 'Droit par rôle',
                'verbose_name_plural': 'Droits par rôle',
                'constraints': [models.UniqueConstraint(fields=('fonctionnalite', 'role'), name='unique_fonctionnalite_role')],
            },
        ),
        migrations.RunPython(creer_fonctionnalites_et_droits, supprimer_fonctionnalites),
    ]
