"""
Django settings for config project.

Generated by 'django-admin startproject' using Django, actuellement testé
avec Django 5.2.16 (voir requirements.txt).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# CORRECTIF SÉCURITÉ : chargement optionnel d'un fichier .env (non commité,
# voir .gitignore) si python-dotenv est installé. Sinon, les variables
# d'environnement système sont utilisées directement (ex: en production).
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# CORRECTIF SÉCURITÉ : la clé n'est plus codée en dur dans le fichier (elle
# avait fuité publiquement sur GitHub). Elle est lue depuis la variable
# d'environnement DJANGO_SECRET_KEY. Une valeur de secours est fournie
# uniquement pour ne pas casser un premier lancement en local, mais elle
# NE DOIT JAMAIS être utilisée en production : définis DJANGO_SECRET_KEY
# dans ton fichier .env (voir .env.example).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-CHANGE-ME-do-not-use-in-production',
)

# CORRECTIF SÉCURITÉ : DEBUG est maintenant piloté par l'environnement.
# Par défaut à False (sûr) ; mets DJANGO_DEBUG=True dans ton .env local
# pour retrouver les pages d'erreur détaillées de Django en développement.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# CORRECTIF : ALLOWED_HOSTS lu depuis l'environnement (liste séparée par
# des virgules, ex: "monsite.fr,www.monsite.fr"). Reste vide par défaut
# en local car Django autorise localhost/127.0.0.1 automatiquement tant
# que DEBUG=True.
_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'interventions',  # L'application finale
    'machines',  # Nouvelle application
    'utilisateurs',  # Notre application
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'utilisateurs.Utilisateur'
LOGIN_URL = 'connexion'
LOGIN_REDIRECT_URL = 'liste_interventions'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'